var searchData=
[
  ['laminas_20i18n_0',['laminas-i18n',['../md_public_2glpi_2vendor_2laminas_2laminas-i18n_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20loader_1',['laminas-loader',['../md_public_2glpi_2vendor_2laminas_2laminas-loader_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20mail_2',['laminas-mail',['../md_public_2glpi_2vendor_2laminas_2laminas-mail_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20mime_3',['laminas-mime',['../md_public_2glpi_2vendor_2laminas_2laminas-mime_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20servicemanager_4',['laminas-servicemanager',['../md_public_2glpi_2vendor_2laminas_2laminas-servicemanager_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20stdlib_5',['laminas-stdlib',['../md_public_2glpi_2vendor_2laminas_2laminas-stdlib_2_r_e_a_d_m_e.html',1,'']]],
  ['laminas_20validator_6',['laminas-validator',['../md_public_2glpi_2vendor_2laminas_2laminas-validator_2_r_e_a_d_m_e.html',1,'']]],
  ['lib_5fautolink_20php_20html_20link_20formatting_20library_7',['lib_autolink - PHP HTML link formatting library',['../md_public_2glpi_2vendor_2iamcal_2lib__autolink_2_r_e_a_d_m_e.html',1,'']]],
  ['library_8',['lib_autolink - PHP HTML link formatting library',['../md_public_2glpi_2vendor_2iamcal_2lib__autolink_2_r_e_a_d_m_e.html',1,'']]],
  ['library_20for_20php_9',['JSON diff/rearrange/patch/pointer library for PHP',['../md_public_2glpi_2vendor_2swaggest_2json-diff_2_r_e_a_d_m_e.html',1,'']]],
  ['license_10',['LICENSE',['../md_public_2glpi_2vendor_2laminas_2laminas-i18n_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-loader_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-mail_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-mime_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-servicemanager_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-stdlib_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2laminas_2laminas-validator_2_l_i_c_e_n_s_e.html',1,'LICENSE']]],
  ['license_11',['License',['../md_public_2glpi_2vendor_2michelf_2php-markdown_2_license.html',1,'']]],
  ['license_12',['LICENSE',['../md_public_2glpi_2vendor_2scssphp_2scssphp_2_l_i_c_e_n_s_e.html',1,'LICENSE'],['../md_public_2glpi_2vendor_2thenetworg_2oauth2-azure_2_l_i_c_e_n_s_e.html',1,'LICENSE']]],
  ['license_13',['The MIT License',['../md_public_2glpi_2vendor_2donatj_2phpuseragentparser_2_l_i_c_e_n_s_e.html',1,'']]],
  ['license_20mit_14',['The MIT License (MIT)',['../md_public_2glpi_2vendor_2psr_2simple-cache_2_l_i_c_e_n_s_e.html',1,'']]],
  ['link_20formatting_20library_15',['lib_autolink - PHP HTML link formatting library',['../md_public_2glpi_2vendor_2iamcal_2lib__autolink_2_r_e_a_d_m_e.html',1,'']]],
  ['lint_16',['JSON Lint',['../md_public_2glpi_2vendor_2seld_2jsonlint_2_r_e_a_d_m_e.html',1,'']]],
  ['liste_20des_20éléments_20obsolètes_17',['Liste des éléments obsolètes',['../deprecated.html',1,'']]],
  ['liste_20des_20choses_20à_20faire_18',['Liste des choses à faire',['../todo.html',1,'']]],
  ['litemoji_20🔥_19',['LitEmoji 🔥',['../md_public_2glpi_2vendor_2elvanto_2litemoji_2_r_e_a_d_m_e.html',1,'']]],
  ['loader_20',['laminas-loader',['../md_public_2glpi_2vendor_2laminas_2laminas-loader_2_r_e_a_d_m_e.html',1,'']]],
  ['log_21',['Log',['../md_public_2glpi_2vendor_2guzzlehttp_2guzzle_2_c_h_a_n_g_e_l_o_g.html',1,'Change Log'],['../md_public_2glpi_2vendor_2guzzlehttp_2psr7_2_c_h_a_n_g_e_l_o_g.html',1,'Change Log'],['../md_public_2glpi_2vendor_2wapmorgan_2unified-archive_2_c_h_a_n_g_e_l_o_g.html',1,'Change Log'],['../md_public_2glpi_2vendor_2psr_2log_2_r_e_a_d_m_e.html',1,'PSR Log']]],
  ['logging_20for_20php_20a_20href_20https_3a_20github_20com_20seldaek_20monolog_20actions_20img_20src_20https_3a_20github_20com_20seldaek_20monolog_20workflows_20continuous_2020integration_20badge_20svg_20branch_20main_20alt_20continuous_20integration_20a_22',['Monolog - Logging for PHP &lt;a href=&quot;https://github.com/Seldaek/monolog/actions&quot; &gt;&lt;img src=&quot;https://github.com/Seldaek/monolog/workflows/Continuous%20Integration/badge.svg?branch=main&quot; alt=&quot;Continuous Integration&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2monolog_2monolog_2_r_e_a_d_m_e.html',1,'']]],
  ['logo_20png_20alt_20sabre_20s_20logo_20sabre_20dav_23',['&lt;img src=&quot;http://sabre.io/img/logo.png&quot; alt=&quot;sabre&apos;s logo&quot;/&gt; sabre/dav',['../md_public_2glpi_2vendor_2sabre_2dav_2_r_e_a_d_m_e.html',1,'']]],
  ['lookup_20feature_24',['Delegate lookup feature',['../md_public_2glpi_2vendor_2container-interop_2container-interop_2docs_2_delegate-lookup.html',1,'']]],
  ['lookup_20feature_20meta_20document_25',['Delegate lookup feature Meta Document',['../md_public_2glpi_2vendor_2container-interop_2container-interop_2docs_2_delegate-lookup-meta.html',1,'']]]
];
