var searchData=
[
  ['s_20logo_20sabre_20dav_0',['&lt;img src=&quot;http://sabre.io/img/logo.png&quot; alt=&quot;sabre&apos;s logo&quot;/&gt; sabre/dav',['../md_public_2glpi_2vendor_2sabre_2dav_2_r_e_a_d_m_e.html',1,'']]],
  ['sabre_20http_1',['sabre/http',['../md_public_2glpi_2vendor_2sabre_2http_2_r_e_a_d_m_e.html',1,'']]],
  ['sabre_20io_20img_20logo_20png_20alt_20sabre_20s_20logo_20sabre_20dav_2',['&lt;img src=&quot;http://sabre.io/img/logo.png&quot; alt=&quot;sabre&apos;s logo&quot;/&gt; sabre/dav',['../md_public_2glpi_2vendor_2sabre_2dav_2_r_e_a_d_m_e.html',1,'']]],
  ['sabre_20vobject_3',['sabre/vobject',['../md_public_2glpi_2vendor_2sabre_2vobject_2_r_e_a_d_m_e.html',1,'']]],
  ['sabre_20xml_4',['sabre/xml',['../md_public_2glpi_2vendor_2sabre_2xml_2_r_e_a_d_m_e.html',1,'']]],
  ['schema_20implementation_20for_20php_5',['Swaggest JSON-schema implementation for PHP',['../md_public_2glpi_2vendor_2swaggest_2json-schema_2_r_e_a_d_m_e.html',1,'']]],
  ['scopeexit_6',['ScopeExit',['../md_public_2glpi_2vendor_2phplang_2scope-exit_2_r_e_a_d_m_e.html',1,'']]],
  ['scssphp_7',['scssphp',['../md_public_2glpi_2vendor_2scssphp_2scssphp_2_r_e_a_d_m_e.html',1,'']]],
  ['sebastian_20diff_8',['sebastian/diff',['../md_public_2glpi_2vendor_2sebastian_2diff_2_r_e_a_d_m_e.html',1,'']]],
  ['security_9',['SECURITY',['../md_public_2glpi_2vendor_2ramsey_2collection_2_s_e_c_u_r_i_t_y.html',1,'']]],
  ['security_20notices_20relating_20to_20phpmailer_10',['Security notices relating to PHPMailer',['../md_public_2glpi_2vendor_2phpmailer_2phpmailer_2_s_e_c_u_r_i_t_y.html',1,'']]],
  ['security_20policy_11',['Security Policy',['../md_public_2glpi_2_s_e_c_u_r_i_t_y.html',1,'Security Policy'],['../md_public_2glpi_2vendor_2brick_2math_2_s_e_c_u_r_i_t_y.html',1,'Security Policy']]],
  ['seldaek_20monolog_20actions_20img_20src_20https_3a_20github_20com_20seldaek_20monolog_20workflows_20continuous_2020integration_20badge_20svg_20branch_20main_20alt_20continuous_20integration_20a_12',['Monolog - Logging for PHP &lt;a href=&quot;https://github.com/Seldaek/monolog/actions&quot; &gt;&lt;img src=&quot;https://github.com/Seldaek/monolog/workflows/Continuous%20Integration/badge.svg?branch=main&quot; alt=&quot;Continuous Integration&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2monolog_2monolog_2_r_e_a_d_m_e.html',1,'']]],
  ['service_20contracts_13',['Symfony Service Contracts',['../md_public_2glpi_2vendor_2symfony_2service-contracts_2_r_e_a_d_m_e.html',1,'']]],
  ['servicemanager_14',['laminas-servicemanager',['../md_public_2glpi_2vendor_2laminas_2laminas-servicemanager_2_r_e_a_d_m_e.html',1,'']]],
  ['simple_20cache_20psr_15',['PHP FIG Simple Cache PSR',['../md_public_2glpi_2vendor_2psr_2simple-cache_2_r_e_a_d_m_e.html',1,'']]],
  ['simplepie_16',['SimplePie',['../md_public_2glpi_2vendor_2simplepie_2simplepie_2_r_e_a_d_m_e.html',1,'']]],
  ['sodium_20compat_17',['Sodium Compat',['../md_public_2glpi_2vendor_2paragonie_2sodium__compat_2_r_e_a_d_m_e.html',1,'']]],
  ['sources_18',['sources',['../md_public_2glpi_2pics_2charts_2sources.html',1,'']]],
  ['specification_19',['Original XML specification',['../md_public_2glpi_2vendor_2glpi-project_2inventory__format_2original.html',1,'']]],
  ['specification_20network_20discovery_20',['Original XML specification (network discovery)',['../md_public_2glpi_2vendor_2glpi-project_2inventory__format_2original-netdiscovery.html',1,'']]],
  ['specification_20network_20inventory_21',['Original XML specification (network inventory)',['../md_public_2glpi_2vendor_2glpi-project_2inventory__format_2original-netinventory.html',1,'']]],
  ['src_20http_3a_20sabre_20io_20img_20logo_20png_20alt_20sabre_20s_20logo_20sabre_20dav_22',['&lt;img src=&quot;http://sabre.io/img/logo.png&quot; alt=&quot;sabre&apos;s logo&quot;/&gt; sabre/dav',['../md_public_2glpi_2vendor_2sabre_2dav_2_r_e_a_d_m_e.html',1,'']]],
  ['src_20https_3a_20github_20com_20seldaek_20monolog_20workflows_20continuous_2020integration_20badge_20svg_20branch_20main_20alt_20continuous_20integration_20a_23',['Monolog - Logging for PHP &lt;a href=&quot;https://github.com/Seldaek/monolog/actions&quot; &gt;&lt;img src=&quot;https://github.com/Seldaek/monolog/workflows/Continuous%20Integration/badge.svg?branch=main&quot; alt=&quot;Continuous Integration&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2monolog_2monolog_2_r_e_a_d_m_e.html',1,'']]],
  ['src_20https_3a_20travis_20ci_20org_20mexitek_20phpcolors_20svg_20branch_20master_20alt_20build_20status_20a_24',['PHPColors &lt;a href=&quot;https://travis-ci.org/mexitek/phpColors&quot; &gt;&lt;img src=&quot;https://travis-ci.org/mexitek/phpColors.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2mexitek_2phpcolors_2_r_e_a_d_m_e.html',1,'']]],
  ['status_20a_25',['PHPColors &lt;a href=&quot;https://travis-ci.org/mexitek/phpColors&quot; &gt;&lt;img src=&quot;https://travis-ci.org/mexitek/phpColors.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2mexitek_2phpcolors_2_r_e_a_d_m_e.html',1,'']]],
  ['stdlib_26',['laminas-stdlib',['../md_public_2glpi_2vendor_2laminas_2laminas-stdlib_2_r_e_a_d_m_e.html',1,'']]],
  ['string_20component_27',['String Component',['../md_public_2glpi_2vendor_2symfony_2string_2_r_e_a_d_m_e.html',1,'']]],
  ['string_20extension_28',['String Extension',['../md_public_2glpi_2vendor_2twig_2string-extra_2_r_e_a_d_m_e.html',1,'']]],
  ['structures_29',['Structures',['../md_public_2glpi_2vendor_2paragonie_2sodium__compat_2src_2_core_2_curve25519_2_r_e_a_d_m_e.html',1,'Curve25519 Data Structures'],['../md_public_2glpi_2vendor_2paragonie_2sodium__compat_2src_2_core32_2_curve25519_2_r_e_a_d_m_e.html',1,'Curve25519 Data Structures']]],
  ['support_30',['GLPI support',['../md_public_2glpi_2_s_u_p_p_o_r_t.html',1,'']]],
  ['svg_20branch_20main_20alt_20continuous_20integration_20a_31',['Monolog - Logging for PHP &lt;a href=&quot;https://github.com/Seldaek/monolog/actions&quot; &gt;&lt;img src=&quot;https://github.com/Seldaek/monolog/workflows/Continuous%20Integration/badge.svg?branch=main&quot; alt=&quot;Continuous Integration&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2monolog_2monolog_2_r_e_a_d_m_e.html',1,'']]],
  ['svg_20branch_20master_20alt_20build_20status_20a_32',['PHPColors &lt;a href=&quot;https://travis-ci.org/mexitek/phpColors&quot; &gt;&lt;img src=&quot;https://travis-ci.org/mexitek/phpColors.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2mexitek_2phpcolors_2_r_e_a_d_m_e.html',1,'']]],
  ['swaggest_20json_20schema_20implementation_20for_20php_33',['Swaggest JSON-schema implementation for PHP',['../md_public_2glpi_2vendor_2swaggest_2json-schema_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20cache_20contracts_34',['Symfony Cache Contracts',['../md_public_2glpi_2vendor_2symfony_2cache-contracts_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20deprecation_20contracts_35',['Symfony Deprecation Contracts',['../md_public_2glpi_2vendor_2symfony_2deprecation-contracts_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20ctype_36',['Symfony Polyfill / Ctype',['../md_public_2glpi_2vendor_2symfony_2polyfill-ctype_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20iconv_37',['Symfony Polyfill / Iconv',['../md_public_2glpi_2vendor_2symfony_2polyfill-iconv_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20mbstring_38',['Symfony Polyfill / Mbstring',['../md_public_2glpi_2vendor_2symfony_2polyfill-mbstring_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20php80_39',['Symfony Polyfill / Php80',['../md_public_2glpi_2vendor_2symfony_2polyfill-php80_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20php81_40',['Symfony Polyfill / Php81',['../md_public_2glpi_2vendor_2symfony_2polyfill-php81_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20polyfill_20php82_41',['Symfony Polyfill / Php82',['../md_public_2glpi_2vendor_2symfony_2polyfill-php82_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20psr_206_20implementation_20for_20caching_42',['Symfony PSR-6 implementation for caching',['../md_public_2glpi_2vendor_2symfony_2cache_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20service_20contracts_43',['Symfony Service Contracts',['../md_public_2glpi_2vendor_2symfony_2service-contracts_2_r_e_a_d_m_e.html',1,'']]],
  ['symfony_20translation_20contracts_44',['Symfony Translation Contracts',['../md_public_2glpi_2vendor_2symfony_2translation-contracts_2_r_e_a_d_m_e.html',1,'']]]
];
