var searchData=
[
  ['parser_0',['PHP User Agent Parser',['../md_public_2glpi_2vendor_2donatj_2phpuseragentparser_2_r_e_a_d_m_e.html',1,'']]],
  ['patch_20pointer_20library_20for_20php_1',['JSON diff/rearrange/patch/pointer library for PHP',['../md_public_2glpi_2vendor_2swaggest_2json-diff_2_r_e_a_d_m_e.html',1,'']]],
  ['php_2',['PHP',['../md_public_2glpi_2vendor_2swaggest_2json-diff_2_r_e_a_d_m_e.html',1,'JSON diff/rearrange/patch/pointer library for PHP'],['../md_public_2glpi_2vendor_2rlanvin_2php-rrule_2_r_e_a_d_m_e.html',1,'RRULE for PHP'],['../md_public_2glpi_2vendor_2swaggest_2json-schema_2_r_e_a_d_m_e.html',1,'Swaggest JSON-schema implementation for PHP']]],
  ['php_20a_20href_20https_3a_20github_20com_20seldaek_20monolog_20actions_20img_20src_20https_3a_20github_20com_20seldaek_20monolog_20workflows_20continuous_2020integration_20badge_20svg_20branch_20main_20alt_20continuous_20integration_20a_3',['Monolog - Logging for PHP &lt;a href=&quot;https://github.com/Seldaek/monolog/actions&quot; &gt;&lt;img src=&quot;https://github.com/Seldaek/monolog/workflows/Continuous%20Integration/badge.svg?branch=main&quot; alt=&quot;Continuous Integration&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2monolog_2monolog_2_r_e_a_d_m_e.html',1,'']]],
  ['php_20fig_20simple_20cache_20psr_4',['PHP FIG Simple Cache PSR',['../md_public_2glpi_2vendor_2psr_2simple-cache_2_r_e_a_d_m_e.html',1,'']]],
  ['php_20html_20link_20formatting_20library_5',['lib_autolink - PHP HTML link formatting library',['../md_public_2glpi_2vendor_2iamcal_2lib__autolink_2_r_e_a_d_m_e.html',1,'']]],
  ['php_20markdown_6',['PHP Markdown',['../md_public_2glpi_2vendor_2michelf_2php-markdown_2_readme.html',1,'']]],
  ['php_20user_20agent_20parser_7',['PHP User Agent Parser',['../md_public_2glpi_2vendor_2donatj_2phpuseragentparser_2_r_e_a_d_m_e.html',1,'']]],
  ['php80_8',['Symfony Polyfill / Php80',['../md_public_2glpi_2vendor_2symfony_2polyfill-php80_2_r_e_a_d_m_e.html',1,'']]],
  ['php81_9',['Symfony Polyfill / Php81',['../md_public_2glpi_2vendor_2symfony_2polyfill-php81_2_r_e_a_d_m_e.html',1,'']]],
  ['php82_10',['Symfony Polyfill / Php82',['../md_public_2glpi_2vendor_2symfony_2polyfill-php82_2_r_e_a_d_m_e.html',1,'']]],
  ['phpcolors_20a_20href_20https_3a_20travis_20ci_20org_20mexitek_20phpcolors_20img_20src_20https_3a_20travis_20ci_20org_20mexitek_20phpcolors_20svg_20branch_20master_20alt_20build_20status_20a_11',['PHPColors &lt;a href=&quot;https://travis-ci.org/mexitek/phpColors&quot; &gt;&lt;img src=&quot;https://travis-ci.org/mexitek/phpColors.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2mexitek_2phpcolors_2_r_e_a_d_m_e.html',1,'']]],
  ['phpcolors_20img_20src_20https_3a_20travis_20ci_20org_20mexitek_20phpcolors_20svg_20branch_20master_20alt_20build_20status_20a_12',['PHPColors &lt;a href=&quot;https://travis-ci.org/mexitek/phpColors&quot; &gt;&lt;img src=&quot;https://travis-ci.org/mexitek/phpColors.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../md_public_2glpi_2vendor_2mexitek_2phpcolors_2_r_e_a_d_m_e.html',1,'']]],
  ['phpmailer_13',['Security notices relating to PHPMailer',['../md_public_2glpi_2vendor_2phpmailer_2phpmailer_2_s_e_c_u_r_i_t_y.html',1,'']]],
  ['png_20alt_20sabre_20s_20logo_20sabre_20dav_14',['&lt;img src=&quot;http://sabre.io/img/logo.png&quot; alt=&quot;sabre&apos;s logo&quot;/&gt; sabre/dav',['../md_public_2glpi_2vendor_2sabre_2dav_2_r_e_a_d_m_e.html',1,'']]],
  ['pointer_20library_20for_20php_15',['JSON diff/rearrange/patch/pointer library for PHP',['../md_public_2glpi_2vendor_2swaggest_2json-diff_2_r_e_a_d_m_e.html',1,'']]],
  ['policy_16',['Policy',['../md_public_2glpi_2_s_e_c_u_r_i_t_y.html',1,'Security Policy'],['../md_public_2glpi_2vendor_2brick_2math_2_s_e_c_u_r_i_t_y.html',1,'Security Policy']]],
  ['polyfill_20ctype_17',['Symfony Polyfill / Ctype',['../md_public_2glpi_2vendor_2symfony_2polyfill-ctype_2_r_e_a_d_m_e.html',1,'']]],
  ['polyfill_20iconv_18',['Symfony Polyfill / Iconv',['../md_public_2glpi_2vendor_2symfony_2polyfill-iconv_2_r_e_a_d_m_e.html',1,'']]],
  ['polyfill_20mbstring_19',['Symfony Polyfill / Mbstring',['../md_public_2glpi_2vendor_2symfony_2polyfill-mbstring_2_r_e_a_d_m_e.html',1,'']]],
  ['polyfill_20php80_20',['Symfony Polyfill / Php80',['../md_public_2glpi_2vendor_2symfony_2polyfill-php80_2_r_e_a_d_m_e.html',1,'']]],
  ['polyfill_20php81_21',['Symfony Polyfill / Php81',['../md_public_2glpi_2vendor_2symfony_2polyfill-php81_2_r_e_a_d_m_e.html',1,'']]],
  ['polyfill_20php82_22',['Symfony Polyfill / Php82',['../md_public_2glpi_2vendor_2symfony_2polyfill-php82_2_r_e_a_d_m_e.html',1,'']]],
  ['promises_23',['Guzzle Promises',['../md_public_2glpi_2vendor_2guzzlehttp_2promises_2_r_e_a_d_m_e.html',1,'']]],
  ['provider_20for_20oauth_202_200_20client_24',['Provider for OAuth 2 0 Client',['../md_public_2glpi_2vendor_2thenetworg_2oauth2-azure_2_r_e_a_d_m_e.html',1,'Azure Active Directory Provider for OAuth 2.0 Client'],['../md_public_2glpi_2vendor_2league_2oauth2-google_2_r_e_a_d_m_e.html',1,'Google Provider for OAuth 2.0 Client']]],
  ['psr_25',['PHP FIG Simple Cache PSR',['../md_public_2glpi_2vendor_2psr_2simple-cache_2_r_e_a_d_m_e.html',1,'']]],
  ['psr_206_20implementation_20for_20caching_26',['Symfony PSR-6 implementation for caching',['../md_public_2glpi_2vendor_2symfony_2cache_2_r_e_a_d_m_e.html',1,'']]],
  ['psr_207_20message_20implementation_27',['PSR-7 Message Implementation',['../md_public_2glpi_2vendor_2guzzlehttp_2psr7_2_r_e_a_d_m_e.html',1,'']]],
  ['psr_207_20usage_28',['PSR-7 Usage',['../md_public_2glpi_2vendor_2psr_2http-message_2docs_2_p_s_r7-_usage.html',1,'']]],
  ['psr_20cache_29',['PSR Cache',['../md_public_2glpi_2vendor_2psr_2cache_2_r_e_a_d_m_e.html',1,'']]],
  ['psr_20http_20message_30',['PSR Http Message',['../md_public_2glpi_2vendor_2psr_2http-message_2_r_e_a_d_m_e.html',1,'']]],
  ['psr_20log_31',['PSR Log',['../md_public_2glpi_2vendor_2psr_2log_2_r_e_a_d_m_e.html',1,'']]],
  ['punycode_32',['Punycode',['../md_public_2glpi_2vendor_2true_2punycode_2_r_e_a_d_m_e.html',1,'']]]
];
